db_connection_str: "mongodb://mongodb:27017"
db_name: "dev_db"
s3_endpoint_url: http://localstack:4566
s3_access_key_id: test
s3_secret_access_key: test
file_metadata_event_topic: metadata
file_metadata_event_type: metadata_upsert
upload_accepted_event_topic: file_ingestion
upload_accepted_event_type: upload_accepted
service_instance_id: 001
kafka_servers: ["kafka:9092"]
