host: 127.0.0.1
port: 8080
log_level: info
workers: 2
auto_reload: False

api_root_path: "/"
openapi_url: "-/openapi.yaml"
docs_url: "/docs"

cors_allowed_origins: ["http://the-other-domain-to-accept.xy"]
cors_allow_credentials: true
cors_allowed_methods: ["*"]
cors_allowed_headers: ["*"]

rabbitmq_host: "rabbitmq"
rabbitmq_port: 5672

db_url: postgresql://admin:admin@postgresql/inbox
db_print_logs: false
s3_endpoint_url: http://upload_controller_service_s3:4566
s3_access_key_id: test
s3_secret_access_key: test
aws_config_ini: None

s3_inbox_bucket_id: inbox
