"""Additional file information in Database

Revision ID: ec66a0a3186b
Revises: 4b41e84f7aac
Create Date: 2022-01-20 17:00:16.089851

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ec66a0a3186b"
down_revision = "4b41e84f7aac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("creation_date", sa.DateTime(), nullable=False))
    op.add_column("files", sa.Column("update_date", sa.DateTime(), nullable=False))
    op.add_column("files", sa.Column("format", sa.String(), nullable=False))
    op.drop_column("files", "registration_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column(
            "registration_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("files", "format")
    op.drop_column("files", "update_date")
    op.drop_column("files", "creation_date")
    # ### end Alembic commands ###
