"""Update to model: added file_name, fixes

Revision ID: acb2553cf589
Revises: cdad7efc63be
Create Date: 2022-01-04 18:04:17.457885

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "acb2553cf589"
down_revision = "cdad7efc63be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("file_name", sa.String(), nullable=False))
    op.drop_constraint("files_study_id_key", "files", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("files_study_id_key", "files", ["study_id"])
    op.drop_column("files", "file_name")
    # ### end Alembic commands ###
