"""study_id_to_grouping_label

Revision ID: 4b41e84f7aac
Revises: acb2553cf589
Create Date: 2022-01-10 15:56:10.770497

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b41e84f7aac"
down_revision = "acb2553cf589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("grouping_label", sa.String(), nullable=False))
    op.alter_column(
        "files",
        "registration_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("files", "study_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("study_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "files",
        "registration_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column("files", "grouping_label")
    # ### end Alembic commands ###
