"""size not nullable

Revision ID: 19e3d538a7cb
Revises: ec66a0a3186b
Create Date: 2022-01-20 17:02:33.458148

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "19e3d538a7cb"
down_revision = "ec66a0a3186b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "size", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("files", "size", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
